#! /usr/bin/env bash

# Autostarts
feh --bg-center ~/.config/wallpaper.png
picom --config ~/.config/picom/picom.conf -b
pgrep -x sxhkd > /dev/null || sxhkd &
bash ~/.config/polybar/material/scripts/pywal.sh ~/.config/wallpaper.png
bash ~/.config/polybar/launch.sh --material

# bspwm config
bspc monitor -d I II III IV V VI

bspc config border_width 2
bspc config normal_border_color "#595959"
bspc config focused_border_color "#33CCFF"
bspc config active_border_color "#33CCFF"

bspc config padding_top 8
bspc config padding_bottom 8
bspc config padding_left 8
bspc config padding_right 8
bspc config window_gap 4

bspc config automatic_scheme alternate
bspc config initial_polarity second_child

bspc config focus_follows_pointer true
bspc config click_to_focus none
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action3 resize_corner
